# Generated by Django 5.2.4 on 2025-08-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tccwebsite', '0002_student_enrollment_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
